config/routes.rb
Rails.application.routes.draw do
  resources :assetgroups

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :channels
  
  resources :channels do
    collection { post :import }
  end
  resources :users

  root 'users#index'

end

app/models/assetgroup.rb
class Assetgroup < ActiveRecord::Base
  belongs_to :user
  has_many :payments, as: :payable
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  belongs_to :user
  has_many :payments, as: :payable
  
  def self.import(file)
    CSV.foreach(file.path, :headers => true, :encoding => 'utf-8') do |row|
      # windows-1251:
      # if row[1]. 'INVALID'
      #   next
      # else
        cleaner = row[0].gsub(/^UC/,"")
          Channel.create(
          cuid:  cleaner,
          title: row[1],
          
        )
      # end
    end
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :payable, polymorphic: true
  # belongs_to :channel
  # belongs_to :assetgroup
end

app/models/user.rb
class User < ActiveRecord::Base
  enum status: [ :paypal, :other ]
  has_many :channels
  has_many :assetgroups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assetgroups_controller.rb
class AssetgroupsController < ApplicationController
  before_action :set_assetgroup, only: [:show, :edit, :update, :destroy]

  # GET /assetgroups
  # GET /assetgroups.json
  def index
    @assetgroups = Assetgroup.all
  end

  # GET /assetgroups/1
  # GET /assetgroups/1.json
  def show
  end

  # GET /assetgroups/new
  def new
    @assetgroup = Assetgroup.new
  end

  # GET /assetgroups/1/edit
  def edit
  end

  # POST /assetgroups
  # POST /assetgroups.json
  def create
    @assetgroup = Assetgroup.new(assetgroup_params)

    respond_to do |format|
      if @assetgroup.save
        format.html { redirect_to @assetgroup, notice: 'Assetgroup was successfully created.' }
        format.json { render :show, status: :created, location: @assetgroup }
      else
        format.html { render :new }
        format.json { render json: @assetgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assetgroups/1
  # PATCH/PUT /assetgroups/1.json
  def update
    respond_to do |format|
      if @assetgroup.update(assetgroup_params)
        format.html { redirect_to @assetgroup, notice: 'Assetgroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @assetgroup }
      else
        format.html { render :edit }
        format.json { render json: @assetgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assetgroups/1
  # DELETE /assetgroups/1.json
  def destroy
    @assetgroup.destroy
    respond_to do |format|
      format.html { redirect_to assetgroups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assetgroup
      @assetgroup = Assetgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assetgroup_params
      params.require(:assetgroup).permit(:guid, :recipient_id, :custom_id)
    end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  def import
    Channel.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:cuid, :title, :user_id_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :first_name, :last_name, :uuid, :email, :paypal_email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assetgroups_helper.rb
module AssetgroupsHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assetgroups/_form.html.erb
<%= form_for(@assetgroup) do |f| %>
  <% if @assetgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assetgroup.errors.count, "error") %> prohibited this assetgroup from being saved:</h2>

      <ul>
      <% @assetgroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guid %><br>
    <%= f.text_field :guid %>
  </div>
  <div class="field">
    <%= f.label :recipient_id %><br>
    <%= f.text_field :recipient_id %>
  </div>
  <div class="field">
    <%= f.label :custom_id %><br>
    <%= f.text_field :custom_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assetgroups/edit.html.erb
<h1>Editing assetgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @assetgroup %> |
<%= link_to 'Back', assetgroups_path %>

app/views/assetgroups/index.html.erb
<h1>Listing assetgroups</h1>

<table>
  <thead>
    <tr>
      <th>Guid</th>
      <th>Recipient</th>
      <th>Custom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assetgroups.each do |assetgroup| %>
      <tr>
        <td><%= assetgroup.guid %></td>
        <td><%= assetgroup.recipient_id %></td>
        <td><%= assetgroup.custom_id %></td>
        <td><%= link_to 'Show', assetgroup %></td>
        <td><%= link_to 'Edit', edit_assetgroup_path(assetgroup) %></td>
        <td><%= link_to 'Destroy', assetgroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assetgroup', new_assetgroup_path %>

app/views/assetgroups/new.html.erb
<h1>New assetgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', assetgroups_path %>

app/views/assetgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guid:</strong>
  <%= @assetgroup.guid %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @assetgroup.recipient_id %>
</p>

<p>
  <strong>Custom:</strong>
  <%= @assetgroup.custom_id %>
</p>

<%= link_to 'Edit', edit_assetgroup_path(@assetgroup) %> |
<%= link_to 'Back', assetgroups_path %>

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cuid %><br>
    <%= f.text_field :cuid %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id_id %><br>
    <%= f.text_field :user_id_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Listing channels</h1>

<table>
  <thead>
    <tr>
      <th>Cuid</th>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.cuid %></td>
        <td><%= channel.title %></td>
        <td><%= channel.user_id %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_tag import_channels_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cuid:</strong>
  <%= @channel.cuid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @channel.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @channel.user_id %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collabstatus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :paypal_email %><br>
    <%= f.text_field :paypal_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://getbootstrap.com/examples/dashboard/dashboard.css">
    
    <li></li>
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Collab</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview</a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <!-- <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul> -->
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4><%= @users.all.size %></h4>
              <span class="text-muted">Total Users</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
    <tr>
      <th>Name</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Uuid</th>
      <th>Paypal Email</th>
      <th colspan="3"></th>
    </tr>

              </thead>
              <tbody>
                <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.paypal_email %></td>
        <td><%= user.last_name %></td>
        <td><%= user.uuid %></td>
        
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

<h1>Listing users</h1>




  <tbody>
    
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>


 <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="http://getbootstrap.com/assets/js/docs.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @user.uuid %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>